In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('excess_mortality.csv')
df.head()

,location,date,p_scores_all_ages,p_scores_15_64,p_scores_65_74,p_scores_75_84,p_scores_85plus,deaths_2020_all_ages,average_deaths_2015_2019_all_ages,deaths_2015_all_ages,...,cum_excess_proj_all_ages,cum_proj_deaths_all_ages,cum_p_proj_all_ages,p_proj_all_ages,p_proj_0_14,p_proj_15_64,p_proj_65_74,p_proj_75_84,p_proj_85p,cum_excess_per_million_proj_all_ages
0,Albania,2020-01-31,-10.65,NaN,NaN,NaN,NaN,2187.0,2447.8,2490.0,...,-247.2,2434.2,-10.16,-10.16,NaN,NaN,NaN,NaN,NaN,-86.044441
1,Albania,2020-02-29,2.17,NaN,NaN,NaN,NaN,2018.0,1975.2,2139.0,...,-190.8,4395.8,-4.34,2.88,NaN,NaN,NaN,NaN,NaN,-66.412942
2,Albania,2020-03-31,0.62,NaN,NaN,NaN,NaN,1993.0,1980.8,2051.0,...,-165.0,6363.0,-2.59,1.31,NaN,NaN,NaN,NaN,NaN,-57.432576
3,Albania,2020-04-30,3.23,NaN,NaN,NaN,NaN,1804.0,1747.6,1906.0,...,-95.0,8097.0,-1.17,4.04,NaN,NaN,NaN,NaN,NaN,-33.067241
4,Albania,2020-05-31,6.15,NaN,NaN,NaN,NaN,1803.0,1698.6,1709.0,...,23.0,9782.0,0.24,7.00,NaN,NaN,NaN,NaN,NaN,8.005753

In [26]:
df[df.location.isin(['Japan'])]

,location,date,p_scores_all_ages,p_scores_15_64,p_scores_65_74,p_scores_75_84,p_scores_85plus,deaths_2020_all_ages,average_deaths_2015_2019_all_ages,deaths_2015_all_ages,...,cum_excess_proj_all_ages,cum_proj_deaths_all_ages,cum_p_proj_all_ages,p_proj_all_ages,p_proj_0_14,p_proj_15_64,p_proj_65_74,p_proj_75_84,p_proj_85p,cum_excess_per_million_proj_all_ages
2896,Japan,2020-01-31,-1.19,NaN,NaN,NaN,NaN,132622.0,134218.8,134256.0,...,-7817.8,140439.8,-5.57,-5.57,NaN,NaN,NaN,NaN,NaN,-62.021028
2897,Japan,2020-02-29,0.65,NaN,NaN,NaN,NaN,117010.0,116254.0,110042.0,...,-13282.8,262914.8,-5.05,-4.46,NaN,NaN,NaN,NaN,NaN,-105.376566
2898,Japan,2020-03-31,1.18,NaN,NaN,NaN,NaN,119161.0,117772.2,113860.0,...,-18115.0,386908.0,-4.68,-3.90,NaN,NaN,NaN,NaN,NaN,-143.711905
2899,Japan,2020-04-30,4.90,NaN,NaN,NaN,NaN,113362.0,108067.8,104886.0,...,-19041.8,501196.8,-3.80,-0.81,NaN,NaN,NaN,NaN,NaN,-151.064496
2900,Japan,2020-05-31,2.53,NaN,NaN,NaN,NaN,108380.0,105704.2,102731.0,...,-22587.0,613122.0,-3.68,-3.17,NaN,NaN,NaN,NaN,NaN,-179.189666
2901,Japan,2020-06-30,2.76,NaN,NaN,NaN,NaN,100423.0,97723.2,94569.0,...,-26108.2,717066.2,-3.64,-3.39,NaN,NaN,NaN,NaN,NaN,-207.124436
2902,Japan,2020-07-31,1.91,NaN,NaN,NaN,NaN,104849.0,102882.8,99448.0,...,-30363.0,826170.0,-3.68,-3.90,NaN,NaN,NaN,NaN,NaN,-240.879082
2903,Japan,2020-08-31,6.19,NaN,NaN,NaN,NaN,111591.0,105087.0,101081.0,...,-30080.0,937478.0,-3.21,0.25,NaN,NaN,NaN,NaN,NaN,-238.633955
2904,Japan,2020-09-30,5.00,NaN,NaN,NaN,NaN,107468.0,102349.6,98242.0,...,-31182.6,1046048.6,-2.98,-1.02,NaN,NaN,NaN,NaN,NaN,-247.381222
2905,Japan,2020-10-31,6.42,NaN,NaN,NaN,NaN,118038.0,110912.4,107928.0,...,-30278.0,1163182.0,-2.60,0.77,NaN,NaN,NaN,NaN,NaN,-240.204750
2906,Japan,2020-11-30,3.99,NaN,NaN,NaN,NaN,118455.0,113915.4,106616.0,...,-31959.4,1283318.4,-2.49,-1.40,NaN,NaN,NaN,NaN,NaN,-253.543817
2907,Japan,2020-12-31,8.27,NaN,NaN,NaN,NaN,133185.0,123008.6,116851.0,...,-28004.0,1412548.0,-1.98,3.06,NaN,NaN,NaN,NaN,NaN,-222.164404
2908,Japan,2021-01-31,4.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-27599.8,1552987.8,-1.78,0.29,NaN,NaN,NaN,NaN,NaN,-218.957760
2909,Japan,2021-02-28,2.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-31090.8,1675462.8,-1.86,-2.85,NaN,NaN,NaN,NaN,NaN,-246.652945
2910,Japan,2021-03-31,4.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-31505.0,1799456.0,-1.75,-0.33,NaN,NaN,NaN,NaN,NaN,-249.938921
2911,Japan,2021-04-30,9.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-27624.8,1913744.8,-1.44,3.40,NaN,NaN,NaN,NaN,NaN,-219.156093
2912,Japan,2021-05-31,12.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-20916.0,2025670.0,-1.03,5.99,NaN,NaN,NaN,NaN,NaN,-165.933105
2913,Japan,2021-06-30,11.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-16126.2,2129614.2,-0.76,4.61,NaN,NaN,NaN,NaN,NaN,-127.934139
2914,Japan,2021-07-31,9.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-13008.0,2238718.0,-0.58,2.86,NaN,NaN,NaN,NaN,NaN,-103.196492
2915,Japan,2021-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2350026.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2916,Japan,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2458596.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
ls=df['location'].value_counts().index.to_list()

In [24]:
ls.sort()

In [25]:
ls

['Albania',
 'Andorra',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Belarus',
 'Belgium',
 'Bermuda',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Brazil',
 'Bulgaria',
 'Canada',
 'Chile',
 'Colombia',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'England & Wales',
 'Estonia',
 'Faeroe Islands',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'Georgia',
 'Germany',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Guadeloupe',
 'Guatemala',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'Iran',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Kazakhstan',
 'Kosovo',
 'Kyrgyzstan',
 'Latvia',
 'Lebanon',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macao',
 'Malaysia',
 'Malta',
 'Martinique',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'North Macedonia',
 'Northern Ireland',
 'Norway',
 'Oman',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Reunion',
 'Romania',
 'Russia',
 'San Marino',
 'Scotland',
 'Serbia',
 'Seychelles',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'South Korea',
 'Spain',
 'Sweden',
 'Switzerland',
 'Taiwan',
 'Thailand',
 'Transnistria',
 'Tunisia',
 'Ukraine',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan']